### ISSUE TITLE
P value for coefficient 

### ISSUE THREAD

**Issue by hallojiang** [bulik/ldsc#100]
Hi Raymond,
How could I get the p-value from coefficient and coefficient SE? I searched many old questions and didn't find the answer. Did I miss something? Could you help me?

Best,
Jiang Quanlong

**Comment by RHReynolds** [comment]
Hi Jiang,
To get the p-value for the coefficient I have been using the coefficient z-score and converting this to a p-value. 
Best,
Regina

**Comment by hallojiang** [comment]
Dear Regina,
I understand. Thanks for your help.

Best,
Jiang Quanlong




Ph.D. Student, Jing-Dong Jackie Han's Lab
CAS-MPG Partner Institute for Computational Biology (PICB)
Shanghai Institutes for Biological Sciences (SIBS)
Chinese Academy of Sciences (CAS)
320 Yueyang Road, Shanghai 200031, P.R.China
 
From: RHReynolds
Date: 2018-01-24 17:10
To: bulik/ldsc
CC: hallojiang; Author
Subject: Re: [bulik/ldsc] P value for coefficient (#100)
Hi Jiang,
To get the p-value for the coefficient I have been using the coefficient z-score and converting this to a p-value.
Best,
Regina

**Comment by rkwalters** [comment]
Yep, that's correct. Thanks for answering this Regina!
Cheers,
Raymond
