### ISSUE TITLE
Test enrichment in new annotations

### ISSUE THREAD

**Issue by yupenghe** [bulik/ldsc#106]
Hi, I am trying to follow the wiki to perform cell type specific (CTS) analysis on the CTS annotations I have.

In one [section](https://github.com/bulik/ldsc/wiki/LD-Score-Estimation-Tutorial#building-on-top-of-the-finucane-et-al-baseline-model), it puts:

Start by downloading `1000G.mac5eur.*`, `hm.*.snp`, and `CNS.*.annot.gz` from [this directory](https://data.broadinstitute.org/alkesgroup/LDSCORE/).

However, the files are not available in the link. I am wondering where I can find some example input files for CTS analysis. Thanks!

Yupeng

**Comment by rkwalters** [comment]
Hi Yupeng,
That’s the correct download directory, but those named files are insides the compressed tar files. This is clarified better in the section before the one you linked, namely that:
- 1000G.mac5eur.* are in 1000G_Phase3_plinkfiles.tgz
- hm.*.snp are in hapmap3_snps.tgz
- CNS.*.annot.gz are in 1000G_Phase3_cell_type_groups.tgz

Hope that helps!

Cheers,
Raymond

**Comment by yupenghe** [comment]
Thanks, I will check it out.

**Comment by yupenghe** [comment]
Thanks again for the help. I really appreciate it. I now have ldsc working properly. 

FYI. It seems that the naming standard has changed. There are no 1000G.mac5eur.* in `1000G_Phase3_frq.tgz` but in `1000G_Phase1_plinkfiles.tgz`. In the former, the prefix of files is 1000G.EUR.QC.*.
