### ISSUE TITLE
Calculating additional information from CTS analysis

### ISSUE THREAD

**Issue by pwh124** [bulik/ldsc#120]
Hello,

I am running through the "Cell type specific analyses" vignette found here: https://github.com/bulik/ldsc/wiki/Cell-type-specific-analyses

Everything comes out pretty much exactly like it is supposed to, however I had one question. 

Is there code available for calculating the "Coefficient (normalized)," "Prop_h2g," and "Prop_SNPs" like what is seen in Table 10b from Finucane et al. 2018 Nat Genet.?

Thanks for your help!

Paul

**Comment by hilaryfinucane** [comment]
Hi Paul,

I'd recommend just running the regressions separately to get that output.
(It requires loading in the .annot files, which we don't do for the
--h2-cts flag.)

Best,
Hilary

**Comment by pwh124** [comment]
Thanks Hilary! 

I realized later last night that may be the way to go but thanks for confirming!

Best,
Paul
