### ISSUE TITLE
Different number of annotations per chromosome

### ISSUE THREAD

**Issue by billgreenwald** [bulik/ldsc#128]
Hi!

I am trying to run LDSC on some data with 15 annotations, and i get the following error:

ValueError: # terms in --M must match # of LD Scores in --ref-ld.

 On one chromosome, only 14 annotations are present, which from looking through the code, I think is causing the problem since n_annots doesnt seem to be set for each chromosome (if I followed the code correctly).

Is there some way to work with data where this happens?

Thanks!

**Comment by rkwalters** [comment]
Hi Bill,
I think the current workaround for this is to merge or regenerate the LD scores as a single file rather than split by chromosome (and use the resulting file with --ref-ld rather than --ref-ld-chr).
Cheers,
Raymond

**Comment by billgreenwald** [comment]
Is there a part of the wiki on merging the LD scores across chromosomes, or creating annotations for all chromosomes?  Do i need to merge the bims?

**Comment by rkwalters** [comment]
Hi Bill,
There's not a wiki section for it. Merging annotations across chromosomes should more-or-less just involve appending the files while making sure you keep SNPs in order and columns lined up. To merge the genetic data you'll probably want to use plink --bmerge (merging just bim files won't keep track of the genetic data in the bed files).
Cheers,
Raymond

**Comment by billgreenwald** [comment]
Sounds good, thanks
