### ISSUE TITLE
Genetic correlation on same data is not 1

### ISSUE THREAD

**Issue by sonia-shah** [bulik/ldsc#130]
I was running genetic correlations for all pairs of traits that I have and noticed that for some traits, even though the genetic correlation was run on the exact same dataset, the genetic correlation was <1 and genetic covariance intercept also <1. 

I see this for the GLGC lipid traits (GWAS+Metabochip), and am wondering if this is to do with the Metabochip SNPs. But I also see it for the CKDGen eGFRcrea_overall phenotype (Gorski et al. 2017 ) which is based on GWAS arrays. For the latter I get a genetic correlation of 0.999 and a genetic covariance intercept of 0.8919.

Thanks

**Comment by rkwalters** [comment]
Hi,

The genetic covariance intercept doesn't necessarily have an expectation of 1 when correlating a trait with itself. Instead, the expectation is that the covariance intercept should be the same as the fitted univariate intercept.

As for the genetic correlation being slightly < 1, that probably reflects slight implementation differences between the --h2 and --rg routines. I haven't fully tracked these down, but things like the implementation of --twostep/--chisq-max, different starting null values for IRWLS, rounding precision in numpy vs. base python numerical operations, etc. are probably enough to yield rg values that aren't exactly 1 (but certainly not different enough to have any practical impact). 

Cheers,
Raymond

**Comment by sonia-shah** [comment]
Thanks Raymond, that's really helpful.
