### ISSUE TITLE
Empty rows in output after running munge_sumstats.py

### ISSUE THREAD

**Issue by vauyeung38** [bulik/ldsc#170]
Hi, I am having a problem with munge_sumstats.py returning an incomplete dataframe after processing summary statistics.

For context, I've downloaded summary statistics from LD Hub (ADHD, 2017 GWAS) and reformatted it to include columns CHR, SNP, BP, A1, A2, EAF, INFO, OR, SE, P and N. Munge_sumstats runs without a problem, but then it prints:
"Writing summary statistics for 1217311 SNPs (1065283 with nonmissing beta) to adhd.sumstats.gz."

This seems to be due to the fact that the alleles don't match with the --merge-alleles list w_hm3.snplist. Is there anything I can do about this?

UPDATE (17/10/19):
I've figured out what the problem is. The munge_sumstats.py script seems to be writing results out for all 1217311 SNPs in the merge-alleles file, regardless of whether the SNPs are in my input file or not. This can be edited post munge_sumstats by subsetting the SNPs to the ones in the input file and then selecting only the ones that could be aligned in the merge-alleles file. 

I'm not sure why this problem happens consistently with my data (it's not just ADHD, but also with other summary statistics I've tried from LD Hub), but I know others have used it without encountering this problem.

**Comment by ape4fld** [comment]
I also ran into the same issue. Thanks for your update, will do the same.

**Comment by SimonYu668** [comment]
I also ran into the same issue. Thanks for your update
