### ISSUE TITLE
Error when calculating LD scores

### ISSUE THREAD

**Issue by Lassana1** [bulik/ldsc#171]
Hi, I am trying to calculate LD scores, and getting this error. Below is my log. Any help is appreciated :)

ln@HGCNT74:~/projects/OLGA_SOL/gds/LDscores> PYTHONPATH=/usr/local/share/ldsc  python /usr/local/share/ldsc/ldsc.py --bfile ../bed/SOL_freeze3xup_chr-22 --l2 --ld-wind-cm 1 --out 1.ld
*********************************************************************
* LD Score Regression (LDSC)
* Version 1.0.1
* (C) 2014-2019 Brendan Bulik-Sullivan and Hilary Finucane
* Broad Institute of MIT and Harvard / MIT Department of Mathematics
* GNU General Public License v3
*********************************************************************
Call:
./ldsc.py \
--ld-wind-cm 1.0 \
--out 1.ld \
--bfile ../bed/SOL_freeze3xup_chr-22 \
--l2

Beginning analysis at Thu Oct 17 12:11:28 2019
Read list of 711309 SNPs from ../bed/SOL_freeze3xup_chr-22.bim
Read list of 12803 individuals from ../bed/SOL_freeze3xup_chr-22.fam
Reading genotypes from ../bed/SOL_freeze3xup_chr-22.bed
After filtering, 710331 SNPs remain
Traceback (most recent call last):
  File "/usr/local/share/ldsc/ldsc.py", line 620, in <module>
    ldscore(args, log)
  File "/usr/local/share/ldsc/ldsc.py", line 298, in ldscore
    raise ValueError(error_msg)
ValueError: Do you really want to compute whole-chomosome LD Score? If so, set the --yes-really flag (warning: it will use a lot of time / memory)

Analysis finished at Thu Oct 17 12:16:01 2019
Total time elapsed: 4.0m:32.63s
Traceback (most recent call last):
  File "/usr/local/share/ldsc/ldsc.py", line 620, in <module>
    ldscore(args, log)
  File "/usr/local/share/ldsc/ldsc.py", line 298, in ldscore
    raise ValueError(error_msg)
ValueError: Do you really want to compute whole-chomosome LD Score? If so, set the --yes-really flag (warning: it will use a lot of time / memory)

**Comment by Lassana1** [comment]
I realized our data does not have cM information. Hence the error. Closing this issue!

**Comment by complexgenome** [comment]
Sorry to bump this. My data don't have cM information either. How do I resolve?

**Comment by ghost** [comment]
> Sorry to bump this. My data don't have cM information either. How do I resolve?

I think you can try --ld-wind-kb if you don't have cM information. It seems working for me.
