### ISSUE TITLE
Can't find munge_sumstats.py script

### ISSUE THREAD

**Issue by r03ert0** [bulik/ldsc#23]
Hello,

Thank you for making ldsc available !

I'm trying to do the LD score tutorial from the wiki, I downloaded the PGC bip and scz files, but I can't find the script munge_sumstats.py. I tried with the script ldsc/ldscore/sumstats.py instead, it produced two .pyc files, but no results. This is the command I used:
python sumstats.py --sumstats $datadir/pgc.cross.scz/pgc.cross.SCZ17.2013-05.txt --N 17115 --out scz

best,
roberto

**Comment by bulik** [comment]
Hi Roberto,

The (half-written) documentation refers to the dev branch (which will soon
become v1.0.0). You can switch to the dev branch with

> git checkout dev

**Comment by r03ert0** [comment]
Thank you Brendan !

and the files for the --ref-ld-chr switch ? I downloaded the
1k_eur_r2_hm3snps_se_weights.RDS file from the ftp link in your Nature
Genetics paper, but it doesn't seem to be the right file...

best,
roberto

**Comment by bulik** [comment]
Correct, that's not the right file (I told NG to remove that link in the
proofs ... annoying).

I'm still working on putting the tutorial together (as evidenced by
$URL_GOES_HERE), but I've just put up some LD Scores that you can download.
These are suitable for European-ancestry GWAS data, including the two
psychiatric datasets used in the genetic correlation tutorial.

http://www.broadinstitute.org/~bulik/eur_ldscores/

**Comment by r03ert0** [comment]
great! everything works now :)
thank you!
