### ISSUE TITLE
HM3 SNPlist is gone or moved

### ISSUE THREAD

**Issue by MichelNivard** [bulik/ldsc#235]
Hi the following file:

https://data.broadinstitute.org/alkesgroup/LDSCORE/w_hm3.snplist.bz2

as used in the tutorial (and for many analyses) is no longer in that place. Others have noted other files are missing. Perhaps time to re-write the tutorial and ensure it all works?

All the best,
Michel

**Comment by yeyixuan** [comment]
It looks like this whole folder https://data.broadinstitute.org/alkesgroup/LDSCORE/ disappeared, looking forward to getting it back soon.

Thanks,
Yixuan

**Comment by ksiewert** [comment]
People in Alkes' group are aware of the issue and working on it. There was too much traffic to those directories, which caused IT to shut it down. They're working on hosting the files elsewhere.

**Comment by jaredbancroft** [comment]
We don't have the redirect in place yet, but you should be able to access everything at alkesgroup.broadinstitute.org. For example [https://alkesgroup.broadinstitute.org/LDSCORE/w_hm3.snplist.bz2](https://alkesgroup.broadinstitute.org/LDSCORE/w_hm3.snplist.bz2) should work.

**Comment by jaredbancroft** [comment]
redirects are in place and all existing links should work again

**Comment by MichelNivard** [comment]
Thanks!

**Comment by sn-GT** [comment]
Is there a new link to download hm3 SNP list file and the EUR reference LD files ? The links provided do not seem to work.

**Comment by rodrigoduarte88** [comment]
Users have to pay now to get access to these files :( 

https://console.cloud.google.com/storage/browser/broad-alkesgroup-public-requester-pays/LDSCORE?pageState=(%22StorageObjectListTable%22:(%22f%22:%22%255B%255D%22))&prefix=&forceOnObjectsSortingFiltering=false&organizationId=0
