### ISSUE TITLE
calculation of tau* from LDSC output

### ISSUE THREAD

**Issue by cmlakhan** [bulik/ldsc#270]
Just for clarification if you use partitioned LD score regression with the flag --print-coefficients then the coefficients are the unnormalized coefficients $/tau$, correct?  If you want the normalized $/tau^*$ then we need to apply the formula below using the Coefficient and Coefficient_std_error columns in the .results file?

![Screen Shot 2021-02-04 at 5 35 50 PM](https://user-images.githubusercontent.com/2146422/106964012-77fa6100-670f-11eb-9a7e-ff932bc1c999.png)

**Comment by dqq0404** [comment]
Hi,
Did you calculate the Tau_star? I do not understand what the meaning of alphabet in this formula.
Which of the following parameters can represent them respectively?
Prop._SNPs	Prop._h2	Prop._h2_std_error	Enrichment	Enrichment_std_error	Enrichment_p	Coefficient	Coefficient_std_error	Coefficient_z-score
