### ISSUE TITLE
munge_sumstats.py: command not found

### ISSUE THREAD

**Issue by iagojunger** [bulik/ldsc#276]
Hello, dear all!

	I’m a beginner in coding, so I’m struggling to run LDSC in Windows’s Ubuntu subsystem. So, my main problem is, I was trying to follow wiki instructions about heritability and genetic correlation, and when I run the command line “munge_sumsstats.py \”, I receive the same message “munge_sumstats.py: command not found”
	Here below I’ll send the print of the error.
        I'm glad if someone could help me :)

all the best,
Iago

![image](https://user-images.githubusercontent.com/76215768/109858797-07c1fb00-7c3b-11eb-86e9-f443117bbfb5.png)

**Comment by nm15336** [comment]
Hi @iagojunger how did you resolve this?

**Comment by MAcc9** [comment]
> Hi @iagojunger how did you resolve this?

I'm guessing this is a path error, please try 
./munge_sumstats.py \
--sumstats pgc.cross.SCZ17.2013-05.txt \
--N 17115 \
--out scz \
--merge-alleles w_hm3.snplist

**Comment by MAcc9** [comment]
> Hi @iagojunger how did you resolve this?

I'm guessing this is a path error, please try
“ ./munge_sumstats.py --sumstats pgc.cross.SCZ17.2013-05.txt --N 17115 --out scz --merge-alleles w_hm3.snplist ”
