### ISSUE TITLE
Appropriate Error Message for missing singed-sumstats

### ISSUE THREAD

**Issue by mkanai** [bulik/ldsc#28]
Hi.

If you don't specify `--signed-sumstats` and there is no name ldsc understands for that, `munge_sunstats.py` now fails with the error below.

```
Traceback (most recent call last):
  File "munge_sumstats.py", line 628, in <module>
    munge_sumstats(parser.parse_args(), p=True)
  File "munge_sumstats.py", line 533, in munge_sumstats
    sign_cname = sign_cnames[0]
IndexError: list index out of range
```

I think more sophisticated error message should be provided by checking `if len(sign_cnames) == 0`.

Thanks.

**Comment by bulik** [comment]
good call; just pushed a fix.
