### ISSUE TITLE
Option for map column to be in Morgans or cM

### ISSUE THREAD

**Issue by jdidion** [bulik/ldsc#29]
The Plink documentation says that the 3rd column of the map file should be in Morgans, so that's how we have coded all our files. I think that ldsc is expecting that column to be cM. Please use Morgans as the default and have an option to use cM instead.

**Comment by bulik** [comment]
The old `plink 1.07` documentation does indeed say Morgans. However, the new `plink 1.9` documentation says either Morgans or cM, and there appears to be a preference for cM, given that the output of the `--cm-map` flag is cM not Morgans.

The only time you need genetic distance in `ldsc` is when defining the window size for computing LD Scores with `--ld-wind-cm`. As a workaround, if you would like to get a 1cM window using a `.bim` file where the third column is in Morgans, you can just use `--ld-wind-cm 0.01`
