### ISSUE TITLE
Number of EUR individuals in 1000 Genomes Project

### ISSUE THREAD

**Issue by xiangzhu** [bulik/ldsc#33]
Thanks for the well-documented software! It is really helpful. After reading the paper and wiki, I am wondering why you used 378 1000 Genomes Europeans individuals in the analysis. It seems that the number of phased EUR individuals is 379.

**Comment by bulik** [comment]
IIRC we removed one individual from a pair of cousins

**Comment by xiangzhu** [comment]
Thanks! I was guessing it might be a pair of twins; if it is cousins, then 378 or 379 are both fine for my application.
