### ISSUE TITLE
no-intercept produces h2=4.84...

### ISSUE THREAD

**Issue by r03ert0** [bulik/ldsc#35]
Hello,
I'm analysing a quantitative trait (brain volume) in a population of unrelated subjects, controlled for population stratification, without genomic control. If I don't constraint the intercept, I obtain:
h2=0.1743 (0.0527)
but if I add the --no-intercept flag, then
h2=4.8404 (0.0757) !
what can be the reason?
thank you in advance!

**Comment by bulik** [comment]
Could you post the log file?

**Comment by r03ert0** [comment]
here it is:

*********************************************************************
* LD Score Regression (LDSC)
* Version 1.0.0
* (C) 2014-2015 Brendan Bulik-Sullivan and Hilary Finucane
* Broad Institute of MIT and Harvard / MIT Department of Mathematics
* GNU General Public License v3
*********************************************************************

Options: 
--h2 ICV.sumstats.gz
--ref-ld-chr LDSCORE/baseline.
--out /Users/roberto/Desktop/ICV
--no-intercept 
--w-ld-chr LDSCORE/weights.

Beginning analysis at Tue Jun 23 18:59:28 2015
Reading summary statistics from ICV.sumstats.gz ...
Read summary statistics for 1068341 SNPs.
Reading reference panel LD Score from LDSCORE/baseline.[1-22] ...
Read reference panel LD Scores for 1189907 SNPs.
Reading regression weight LD Score from LDSCORE/weights.[1-22] ...
Read regression weight LD Scores for 1242190 SNPs.
After merging with reference panel LD, 1066566 SNPs remain.
After merging with regression SNP LD, 1063925 SNPs remain.
Removed 0 SNPs with chi^2 > 80 (1063925 SNPs remain)
Total Observed scale h2: 4.8408 (0.0757)
Categories: base_0 Coding_UCSC_0 Coding_UCSC.extend.500_0 Conserved_LindbladToh_0 Conserved_LindbladToh.extend.500_0 CTCF_Hoffman_0 CTCF_Hoffman.extend.500_0 DGF_ENCODE_0 DGF_ENCODE.extend.500_0 DHS_peaks_Trynka_0 DHS_Trynka_0 DHS_Trynka.extend.500_0 Enhancer_Andersson_0 Enhancer_Andersson.extend.500_0 Enhancer_Hoffman_0 Enhancer_Hoffman.extend.500_0 FetalDHS_Trynka_0 FetalDHS_Trynka.extend.500_0 H3K27ac_Hnisz_0 H3K27ac_Hnisz.extend.500_0 H3K27ac_PGC2_0 H3K27ac_PGC2.extend.500_0 H3K4me1_peaks_Trynka_0 H3K4me1_Trynka_0 H3K4me1_Trynka.extend.500_0 H3K4me3_peaks_Trynka_0 H3K4me3_Trynka_0 H3K4me3_Trynka.extend.500_0 H3K9ac_peaks_Trynka_0 H3K9ac_Trynka_0 H3K9ac_Trynka.extend.500_0 Intron_UCSC_0 Intron_UCSC.extend.500_0 PromoterFlanking_Hoffman_0 PromoterFlanking_Hoffman.extend.500_0 Promoter_UCSC_0 Promoter_UCSC.extend.500_0 Repressed_Hoffman_0 Repressed_Hoffman.extend.500_0 SuperEnhancer_Hnisz_0 SuperEnhancer_Hnisz.extend.500_0 TFBS_ENCODE_0 TFBS_ENCODE.extend.500_0 Transcribed_Hoffman_0 Transcribed_Hoffman.extend.500_0 TSS_Hoffman_0 TSS_Hoffman.extend.500_0 UTR_3_UCSC_0 UTR_3_UCSC.extend.500_0 UTR_5_UCSC_0 UTR_5_UCSC.extend.500_0 WeakEnhancer_Hoffman_0 WeakEnhancer_Hoffman.extend.500_0
Observed scale h2: -1.3225 -0.0512  0.1766  0.3732 -0.0918 -0.2027  0.6231 -0.4405  0.9919 -0.1491 -0.1309  1.6781 -0.0649  0.1261 -0.0583 -0.4509 -0.0691  1.6653  0.8158 -0.9677  0.1593 -0.4617  0.3165 -1.0034  2.1976  0.0843  0.2893 -0.3945  0.1875 -0.8899  0.7366 -1.5568  1.4326 -0.1068 -0.0724  0.115  -0.0948  0.4398  0.1164  0.4274 -0.257   0.7446 -0.1407 -1.1031  0.8978 -0.1034  0.145   0.047  -0.0524  0.0414 -0.1579  0.1799  0.227
Observed scale h2 SE: 0.6792  0.0593  0.0981  0.0784  0.1786  0.0887  0.12    0.2334  0.3914  0.28    0.3406  0.4296  0.0384  0.056   0.1565  0.2525  0.2     0.2808  0.7109  0.7766  0.4399  0.4795  0.2398  0.5244  0.5317  0.1092  0.2069  0.2642  0.1088  0.2267  0.2697  1.8905  1.9415  0.0455  0.0684  0.1913  0.1988  0.4135  0.5323  1.0544  1.0665  0.2324  0.3375  0.274   0.5095  0.0842  0.1004  0.0431  0.0526  0.0253  0.0503  0.072   0.1564
Proportion of SNPs: 0.0886  0.0013  0.0057  0.0023  0.0295  0.0021  0.0063  0.0122  0.048   0.0099  0.0149  0.0442  0.0004  0.0017  0.0056  0.0136  0.0075  0.0252  0.0347  0.0374  0.0239  0.0298  0.0152  0.0378  0.054   0.0037  0.0118  0.0226  0.0034  0.0112  0.0204  0.0343  0.0352  0.0007  0.003   0.0028  0.0034  0.0409  0.0637  0.0149  0.0152  0.0117  0.0304  0.0306  0.0676  0.0016  0.0031  0.001   0.0024  0.0005  0.0025  0.0019  0.0079
Proportion of h2g: -0.2732 -0.0106  0.0365  0.0771 -0.019  -0.0419  0.1287 -0.091   0.2049 -0.0308 -0.027   0.3467 -0.0134  0.026  -0.012  -0.0932 -0.0143  0.344   0.1685 -0.1999  0.0329 -0.0954  0.0654 -0.2073  0.454   0.0174  0.0598 -0.0815  0.0387 -0.1838  0.1522 -0.3216  0.2959 -0.0221 -0.015   0.0238 -0.0196  0.0908  0.024   0.0883 -0.0531  0.1538 -0.0291 -0.2279  0.1855 -0.0214  0.0299  0.0097 -0.0108  0.0085 -0.0326  0.0372  0.0469
Enrichment: -3.0838  -8.1403   6.3791  33.3916  -0.6441 -19.8315  20.4461  -7.4657   4.2714  -3.1101  -1.8199   7.8455 -34.9244  15.4148  -2.1455  -6.8312  -1.902   13.625    4.8632  -5.3398   1.3781  -3.2036   4.3086  -5.4853   8.4123   4.7057   5.0607  -3.6004  11.2781 -16.4551   7.4493  -9.3693   8.4117 -29.5413  -5.0449   8.6061  -5.7226   2.2234   0.3775   5.9178  -3.492   13.1093  -0.9551  -7.4468   2.7437 -13.2383   9.7065   9.9235  -4.5408  17.7907 -13.2438  19.8895   5.9516
Coefficients: -2.2314e-07  -5.8902e-07   4.6158e-07   2.4162e-06  -4.6606e-08  -1.4350e-06   1.4795e-06  -5.4021e-07   3.0908e-07  -2.2504e-07  -1.3169e-07   5.6769e-07  -2.5271e-06   1.1154e-06  -1.5525e-07  -4.9430e-07  -1.3763e-07   9.8589e-07   3.5189e-07  -3.8638e-07   9.9721e-08  -2.3181e-07   3.1177e-07  -3.9691e-07   6.0871e-07   3.4050e-07   3.6619e-07  -2.6052e-07   8.1607e-07  -1.1907e-06   5.3902e-07  -6.7795e-07   6.0866e-07  -2.1376e-06  -3.6504e-07   6.2273e-07  -4.1408e-07   1.6088e-07   2.7316e-08   4.2821e-07  -2.5268e-07   9.4858e-07  -6.9110e-08  -5.3884e-07   1.9853e-07  -9.5790e-07   7.0235e-07   7.1805e-07  -3.2857e-07   1.2873e-06  -9.5831e-07   1.4392e-06   4.3065e-07
Coefficient SE: 1.1461e-07   6.8259e-07   2.5644e-07   5.0761e-07   9.0636e-08   6.2835e-07   2.8488e-07   2.8620e-07   1.2195e-07   4.2264e-07   3.4259e-07   1.4534e-07   1.4962e-06   4.9562e-07   4.1695e-07   2.7677e-07   3.9807e-07   1.6623e-07   3.0665e-07   3.1010e-07   2.7546e-07   2.4078e-07   2.3617e-07   2.0742e-07   1.4727e-07   4.4088e-07   2.6193e-07   1.7446e-07   4.7360e-07   3.0327e-07   1.9732e-07   8.2329e-07   8.2489e-07   9.1150e-07   3.4493e-07   1.0360e-06   8.6858e-07   1.5126e-07   1.2491e-07   1.0563e-06   1.0487e-06   2.9609e-07   1.6581e-07   1.3384e-07   1.1267e-07   7.8025e-07   4.8667e-07   6.5800e-07   3.2933e-07   7.8755e-07   3.0539e-07   5.7599e-07   2.9661e-07
Lambda GC: 1.0527
Mean Chi^2: 1.0576
Intercept: constrained to 1
Analysis finished at Tue Jun 23 19:00:29 2015
Total time elapsed: 1.0m:0.4s

**Comment by hilaryfinucane** [comment]
Could you also post the log file from the analysis where the heritability
estimate was smaller?

Also, what is your sample size?

Best,

Hilary

**Comment by r03ert0** [comment]
Hi Hilary,
here's the log of the run without constrained intercept.
sample size: 11,373 subjects
thank you!
roberto
(also, 'ratio' is very high for ICV, ~30%, however, I also obtain h2~4 for other phenotypes where ratio<20%)

*********************************************************************
* LD Score Regression (LDSC)
* Version 1.0.0
* (C) 2014-2015 Brendan Bulik-Sullivan and Hilary Finucane
* Broad Institute of MIT and Harvard / MIT Department of Mathematics
* GNU General Public License v3
*********************************************************************

Options: 
--h2 ICV.sumstats.gz
--ref-ld-chr LDSCORE/baseline.
--out /Users/roberto/Desktop/ICV
--w-ld-chr LDSCORE/weights.

Beginning analysis at Tue Jun 23 18:56:16 2015
Reading summary statistics from ICV.sumstats.gz ...
Read summary statistics for 1068341 SNPs.
Reading reference panel LD Score from LDSCORE/baseline.[1-22] ...
Read reference panel LD Scores for 1189907 SNPs.
Reading regression weight LD Score from LDSCORE/weights.[1-22] ...
Read regression weight LD Scores for 1242190 SNPs.
After merging with reference panel LD, 1066566 SNPs remain.
After merging with regression SNP LD, 1063925 SNPs remain.
Removed 0 SNPs with chi^2 > 80 (1063925 SNPs remain)
Total Observed scale h2: 0.1743 (0.0527)
Categories: base_0 Coding_UCSC_0 Coding_UCSC.extend.500_0 Conserved_LindbladToh_0 Conserved_LindbladToh.extend.500_0 CTCF_Hoffman_0 CTCF_Hoffman.extend.500_0 DGF_ENCODE_0 DGF_ENCODE.extend.500_0 DHS_peaks_Trynka_0 DHS_Trynka_0 DHS_Trynka.extend.500_0 Enhancer_Andersson_0 Enhancer_Andersson.extend.500_0 Enhancer_Hoffman_0 Enhancer_Hoffman.extend.500_0 FetalDHS_Trynka_0 FetalDHS_Trynka.extend.500_0 H3K27ac_Hnisz_0 H3K27ac_Hnisz.extend.500_0 H3K27ac_PGC2_0 H3K27ac_PGC2.extend.500_0 H3K4me1_peaks_Trynka_0 H3K4me1_Trynka_0 H3K4me1_Trynka.extend.500_0 H3K4me3_peaks_Trynka_0 H3K4me3_Trynka_0 H3K4me3_Trynka.extend.500_0 H3K9ac_peaks_Trynka_0 H3K9ac_Trynka_0 H3K9ac_Trynka.extend.500_0 Intron_UCSC_0 Intron_UCSC.extend.500_0 PromoterFlanking_Hoffman_0 PromoterFlanking_Hoffman.extend.500_0 Promoter_UCSC_0 Promoter_UCSC.extend.500_0 Repressed_Hoffman_0 Repressed_Hoffman.extend.500_0 SuperEnhancer_Hnisz_0 SuperEnhancer_Hnisz.extend.500_0 TFBS_ENCODE_0 TFBS_ENCODE.extend.500_0 Transcribed_Hoffman_0 Transcribed_Hoffman.extend.500_0 TSS_Hoffman_0 TSS_Hoffman.extend.500_0 UTR_3_UCSC_0 UTR_3_UCSC.extend.500_0 UTR_5_UCSC_0 UTR_5_UCSC.extend.500_0 WeakEnhancer_Hoffman_0 WeakEnhancer_Hoffman.extend.500_0
Observed scale h2: -0.1019 -0.0477  0.1277  0.1067 -0.0816 -0.1363  0.2713 -0.0062  0.3536  0.0616 -0.1858  0.1957 -0.0266 -0.0148 -0.0211 -0.2937 -0.173  -0.1533  0.1698 -0.2379  0.2707 -0.3084  0.2828  0.0225 -0.08   -0.1075  0.2689 -0.2008  0.0978 -0.3781  0.4716  0.7258 -0.7615 -0.0388  0.0513  0.0727 -0.0733  0.0459  0.0719  0.386  -0.3124  0.5836 -0.5835  0.126  -0.2301  0.0385 -0.0016  0.0104 -0.0499  0.0109 -0.0767 -0.0318  0.0649
Observed scale h2 SE: 0.2861  0.043   0.0669  0.0492  0.1028  0.0708  0.1019  0.1824  0.2843  0.2147  0.2671  0.3462  0.0304  0.0424  0.124   0.1894  0.1599  0.2311  0.625   0.6795  0.3655  0.3928  0.1959  0.372   0.3667  0.0833  0.1554  0.1771  0.0838  0.174   0.1983  1.279   1.307   0.0358  0.055   0.1469  0.154   0.2198  0.3235  0.8178  0.8312  0.1742  0.2457  0.1571  0.2766  0.0658  0.0759  0.0403  0.0396  0.0216  0.0377  0.0559  0.0981
Proportion of SNPs: 0.0886  0.0013  0.0057  0.0023  0.0295  0.0021  0.0063  0.0122  0.048   0.0099  0.0149  0.0442  0.0004  0.0017  0.0056  0.0136  0.0075  0.0252  0.0347  0.0374  0.0239  0.0298  0.0152  0.0378  0.054   0.0037  0.0118  0.0226  0.0034  0.0112  0.0204  0.0343  0.0352  0.0007  0.003   0.0028  0.0034  0.0409  0.0637  0.0149  0.0152  0.0117  0.0304  0.0306  0.0676  0.0016  0.0031  0.001   0.0024  0.0005  0.0025  0.0019  0.0079
Proportion of h2g: -0.5843 -0.2737  0.7326  0.6122 -0.4683 -0.7816  1.5562 -0.0354  2.0285  0.3533 -1.0659  1.1224 -0.1528 -0.0849 -0.1212 -1.6849 -0.9925 -0.8794  0.9743 -1.3647  1.5526 -1.7689  1.6222  0.1292 -0.4591 -0.6166  1.5424 -1.1517  0.5608 -2.1687  2.7054  4.1634 -4.3681 -0.2223  0.2945  0.4171 -0.4207  0.2631  0.4123  2.2143 -1.792   3.3475 -3.3473  0.7229 -1.3199  0.2209 -0.009   0.0595 -0.2863  0.0625 -0.4398 -0.1824  0.3721
Enrichment: -6.5956 -210.7377  128.0999  265.1679  -15.8969 -370.2442  247.2068   -2.9016   42.285    35.6804  -71.7216   25.4009 -397.769   -50.28    -21.605  -123.557  -132.1794  -34.8281   28.115   -36.4527   65.0384  -59.4223  106.8863    3.4191   -8.5072 -166.5447  130.6022  -50.8849  163.2844 -194.1202  132.441   121.2958 -124.16   -297.8092   99.3275  151.0758 -122.9295    6.4398    6.472   148.4129 -117.8779  285.2906 -110.016    23.6224  -19.5257  136.8614   -2.9197   60.7634 -120.0043  130.0739 -178.5434  -97.6117   47.218
Coefficients: -1.7187e-08  -5.4916e-07   3.3381e-07   6.9100e-07  -4.1425e-08  -9.6481e-07   6.4419e-07  -7.5612e-09   1.1019e-07   9.2979e-08  -1.8690e-07   6.6192e-08  -1.0365e-06  -1.3102e-07  -5.6300e-08  -3.2197e-07  -3.4444e-07  -9.0758e-08   7.3264e-08  -9.4991e-08   1.6948e-07  -1.5485e-07   2.7853e-07   8.9097e-09  -2.2169e-08  -4.3400e-07   3.4033e-07  -1.3260e-07   4.2550e-07  -5.0585e-07   3.4513e-07   3.1608e-07  -3.2355e-07  -7.7605e-07   2.5884e-07   3.9369e-07  -3.2034e-07   1.6781e-08   1.6865e-08   3.8675e-07  -3.0718e-07   7.4343e-07  -2.8669e-07   6.1557e-08  -5.0882e-08   3.5664e-07  -7.6084e-09   1.5834e-07  -3.1272e-07   3.3896e-07  -4.6526e-07  -2.5436e-07   1.2304e-07
Coefficient SE: 4.8268e-08   4.9468e-07   1.7489e-07   3.1840e-07   5.2170e-08   5.0154e-07   2.4193e-07   2.2372e-07   8.8580e-08   3.2415e-07   2.6869e-07   1.1712e-07   1.1838e-06   3.7496e-07   3.3034e-07   2.0758e-07   3.1836e-07   1.3681e-07   2.6961e-07   2.7131e-07   2.2888e-07   1.9725e-07   1.9291e-07   1.4714e-07   1.0157e-07   3.3631e-07   1.9666e-07   1.1699e-07   3.6457e-07   2.3277e-07   1.4513e-07   5.5699e-07   5.5531e-07   7.1628e-07   2.7743e-07   7.9559e-07   6.7264e-07   8.0424e-08   7.5921e-08   8.1931e-07   8.1724e-07   2.2196e-07   1.2069e-07   7.6765e-08   6.1171e-08   6.0979e-07   3.6773e-07   6.1534e-07   2.4824e-07   6.7338e-07   2.2868e-07   4.4752e-07   1.8598e-07
Lambda GC: 1.0527
Mean Chi^2: 1.0576
Intercept: 1.0175 (0.008)
Ratio: 0.3036 (0.138)
Analysis finished at Tue Jun 23 18:57:17 2015
Total time elapsed: 1.0m:0.6s

**Comment by hilaryfinucane** [comment]
Okay, a few more questions:

(1) It looks like you might be using an older version. Could you try git
pull and check that that doesn't fix the problem?
(2) Was there any custom array data in the dataset?
(3) Could you run the analysis with --ref-ld-chr weights. instead of
--ref-ld-chr baseline. and send me the log files with and w/o intercept?

Thanks,

Hilary

**Comment by r03ert0** [comment]
(1) updating to the most recent version seems to solve it :D Now I get
"Total Observed scale h2: 0.2545 (0.0326)" with intercept constrained, and
"h2: 0.1743 (0.0527)" without intercept constrained.
(2) no
(3) running the analysis with --ref-ld-chr weights. throws an error:

Beginning analysis at Thu Jun 25 21:10:41 2015
Reading summary statistics from ICV.sumstats.gz ...
Read summary statistics for 1068341 SNPs.
Reading reference panel LD Score from
/Applications/_Geno/LDSCORE/weights.[1-22] ...
Read reference panel LD Scores for 1242190 SNPs.
Traceback (most recent call last):
  File "/Applications/_Geno/ldsc/ldsc.py", line 630, in <module>
    sumstats.estimate_h2(args, log)
  File "/Applications/_Geno/ldsc/ldscore/sumstats.py", line 260, in
estimate_h2
    args, log, args.h2)
  File "/Applications/_Geno/ldsc/ldscore/sumstats.py", line 239, in
_read_ld_sumstats
    M_annot = _read_M(args, log, n_annot)
  File "/Applications/_Geno/ldsc/ldscore/sumstats.py", line 116, in _read_M
    _splitp(args.ref_ld_chr), _N_CHR, common=(not args.not_M_5_50))
  File "/Applications/_Geno/ldsc/ldscore/parse.py", line 167, in M_fromlist
    return np.hstack([M(fh, num, N, common) for fh in flist])
  File "/Applications/_Geno/ldsc/ldscore/parse.py", line 158, in M
    x = np.sum([parsefunc(sub_chr(fh, i) + suffix) for i in xrange(1, num +
1)], axis=0)
  File "/Applications/_Geno/ldsc/ldscore/parse.py", line 152, in <lambda>
    parsefunc = lambda y: [float(z) for z in open(y,
'r').readline().split()]
IOError: [Errno 2] No such file or directory:
'/Applications/_Geno/LDSCORE/weights.1.l2.M_5_50'

I don't have any file called "weights.1.l2.M_5_50" in my LDSCORE directory.
Should I get a newer version of the weights as well?

thank you for your help!!

best,
roberto

**Comment by hilaryfinucane** [comment]
Ah oops, I forgot I hadn't included those files. If things are working now,
I'd just skip that extra debug step.

Best,

Hilary

**Comment by r03ert0** [comment]
great! thank you
