### ISSUE TITLE
eas_ldscores.tar.bz2

### ISSUE THREAD

**Issue by 1667857557** [bulik/ldsc#382]
Hello, can anybody shares the file"eas_ldscores.tar.bz2" with me? the website https://alkesgroup.broadinstitute.org/LDSCORE/ did not available now, this is my email, thanks in advance!!!

**Comment by TianTTL** [comment]
The file has been sent.

The description of new file storage address is [here](https://storage.googleapis.com/broad-alkesgroup-public/LDSCORE/README_new_data_location.txt)
> Due to excessive data transfer costs, this directory is now available on a requester-pays basis at 
https://console.cloud.google.com/storage/browser/broad-alkesgroup-public-requester-pays.

**Comment by wbm1999** [comment]
Hello, I also meet this problem now. And I can't download it from google storage. Could you please send  the file "eas_ldscores.tar.bz2"  to 1700012173@pku.edu.cn? Really thanks a lot! @TianTTL @1667857557

**Comment by JiaruiMi** [comment]
Hi, would you please also send me this file. My email address is jiarui.mi@zju.edu.cn. Thanks for sharing and all the best!

**Comment by Akki-akki** [comment]
Hi, would you please also send me this file. my email address is 22211020104@m.fudan.edu.cn. thank you very much!! best wishes.

**Comment by TianTTL** [comment]
Dear all,

You can download the file from the following link: [eas_ldscores.tar.bz2](https://drive.google.com/file/d/1BtpWx02ON33KfjyCFSdmoWYlMZWImh2f/view?usp=sharing).

If it's against community rules to share this file publicly, please let me know.

Wishing you all the best in your research.
@wbm1999 @JiaruiMi @Akki-akki

**Comment by Liuzhongying007** [comment]
Hi, would you please also send me this file. my email address is liuzhongying2023@gmail.com. thank you very much!! best wishes.

**Comment by abright087** [comment]
Thanks for sharing this file. It has been helpful!
