### ISSUE TITLE
./ldsc.py -h ERROR

### ISSUE THREAD

**Issue by zkutalik** [bulik/ldsc#39]
Hi,

I just installed ldsc, seem to have all the python packages installed, but still get this message:

-bash-4.1$ ./ldsc.py -h
Traceback (most recent call last):
  File "./ldsc.py", line 13, in <module>
    import ldscore.parse as ps
  File "/data/sgg/zoltan/bin/ldsc/ldscore/parse.py", line 100
    new_col_dict = {c: c + '_' + str(i) for c in y.columns if c != 'SNP'}
                                          ^
SyntaxError: invalid syntax

Does it give you a hint what may have gone wrong?

Thanks a lot

Zoltan

**Comment by hilaryfinucane** [comment]
Hi Zoltan,

Try python ldsc.py -h?

Hilary

**Comment by zkutalik** [comment]
Thanks, I tried that too, but I still get the same error message.

Zoltan

**Comment by hilaryfinucane** [comment]
Hi Zoltan,

What does "git status" give you?

Hilary

**Comment by zkutalik** [comment]
-bash-4.1$ git status
# On branch master
# Changed but not updated:
#   (use "git add <file>..." to update what will be committed)
#   (use "git checkout -- <file>..." to discard changes in working directory)
#
#       modified:   ldscore/__init__.py
#       modified:   ldscore/irwls.py
#       modified:   ldscore/jackknife.py
#       modified:   ldscore/ldscore.py
#       modified:   ldscore/parse.py
#       modified:   ldscore/regressions.py
#       modified:   ldscore/sumstats.py
#       modified:   test/simulate.py
#       modified:   test/test_irwls.py
#       modified:   test/test_jackknife.py
#       modified:   test/test_ldscore.py
#       modified:   test/test_munge_sumstats.py
#       modified:   test/test_parse.py
#       modified:   test/test_regressions.py
#       modified:   test/test_sumstats.py
#
no changes added to commit (use "git add" and/or "git commit -a")


Thanks

Zoltan

**Comment by hilaryfinucane** [comment]
It looks like you've changed some of the files?

To reset to the version on github, try:
git reset --hard
git pull

**Comment by zkutalik** [comment]
I did as you suggested, but still the same error:

-bash-4.1$ git reset --hard
HEAD is now at 78874c7 clarify error message with mismatched alleles in --rg when munge_sumstats run without --merge-alleles flag
-bash-4.1$ git pull
Already up-to-date.
-bash-4.1$ ./ldsc.py -h
Traceback (most recent call last):
  File "./ldsc.py", line 13, in <module>
    import ldscore.parse as ps
  File "/data/sgg/zoltan/bin/ldsc/ldscore/parse.py", line 100
    new_col_dict = {c: c + '_' + str(i) for c in y.columns if c != 'SNP'}
                                          ^
SyntaxError: invalid syntax

**Comment by hilaryfinucane** [comment]
Hi Zoltan,

What Python version are you running?

Hilary

**Comment by zkutalik** [comment]
Python 2.6.6

Shall I update to the latest?

**Comment by hilaryfinucane** [comment]
You should update to Python 2.7. ldsc is not compatible with Python 2.6 or
Python 3.

Let me know if that fixes the problem,

Hilary

**Comment by zkutalik** [comment]
Thanks, I'll do so and get back to you.

Zoltan

**Comment by zkutalik** [comment]
Many thanks, I updated python to 2.7.8 and it fixed the problem! :)
