### ISSUE TITLE
s-LDSC continuous annotations

### ISSUE THREAD

**Issue by aiim-lab** [bulik/ldsc#394]
**AIM**: To produce continuous annotation files in UCSC bed format to perform partition LDSC using the continuous annotation files (I am following: [[https://kevinlkx.github.io/analysis_pipelines/sldsc_pipeline.html#compute_ld_scores_for_continuous_annotations](https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fkevinlkx.github.io%2Fanalysis_pipelines%2Fsldsc_pipeline.html%23compute_ld_scores_for_continuous_annotations&data=05%7C01%7Cmanpreet.singh.1%40umontreal.ca%7C1b61727ba3a748fd875c08db7f232e53%7Cd27eefec2a474be7981e0f8977fa31d8%7C1%7C0%7C638243561295366580%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=WsXqLnSTKbBGUs5FTIbm4aTa3PEOg28wj1cRDAkT1fY%3D&reserved=0)]

**Hiccup**: I have plink files (bim, bed, fam) for :
1000G.EUR.QC.
which I hope could be used to produce continuous annotations and which eventually can be used in partition heritability analysis as :
python ldsc.py \
--h2 ${TRAIT}.sumstats.gz \
--ref-ld-chr baselineLD.,${ANNOT}. \
--frqfile-chr 1000G_Phase3_frq/1000G.EUR.QC. \
--w-ld-chr 1000G_Phase3_weights_hm3_no_MHC/weights.hm3_noMHC. \
--overlap-annot --print-cov --print-coefficients --print-delete-vals \
--out ${TRAIT}_${ANNOT}_baselineLD
where ${ANNOT} are the continuous annotations, I want to produce.

Thus, I want to figure out, how to produce these continuous annotations files which will eventually be used in partition heritability analysis and whose format should look like: ("chr", "start", "end", "value") as per the script: [[https://github.com/kevinlkx/analysis_pipelines/blob/master/code/make_ldsc_continuous_annot.R](https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fkevinlkx%2Fanalysis_pipelines%2Fblob%2Fmaster%2Fcode%2Fmake_ldsc_continuous_annot.R&data=05%7C01%7Cmanpreet.singh.1%40umontreal.ca%7C1b61727ba3a748fd875c08db7f232e53%7Cd27eefec2a474be7981e0f8977fa31d8%7C1%7C0%7C638243561295366580%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=q%2FnOfpihKBqE3lrFAlyKbIJ2AytFKs0A3aREJ1nEbnw%3D&reserved=0)]

**Comment by aksarkar** [comment]
Continuous annotations are typically the output of some other method/pipeline. In general, that other pipeline produces one value per SNP.

Without more information, it is not possible to help you produce continuous annotation files.

**Comment by aiim-lab** [comment]
I figured that continuous annotations are produced from some other pipeline. So, I grabbed them from pre-existing databases (cao et all) and using them in partition heritability analysis using LDSC. Closing the issue.
