### ISSUE TITLE
Incorrect command in tutorial? --out to wrong file?

### ISSUE THREAD

**Issue by aaronmcdaid** [bulik/ldsc#41]
Near the top of 'Heritability and Genetic Correlation', there is a command just after _"If you just want to compute heritability and the LD Score regression intercept, replace the last two commands with "_

I think this command should be something like `--out scz` instead of `--out scz_bip`. The important thing is that it matches the command on the `less` line in the immediately following line.

Also, it might help to insert a space just before the `\` as part of the `--h2` parameter on the same command

**Comment by rkwalters** [comment]
Thanks @aaronmcdaid, good suggestions on both counts. The tutorial's been edited accordingly.
