### ISSUE TITLE
Run failure

### ISSUE THREAD

**Issue by tushardave26** [bulik/ldsc#42]
Hello Folks,

I would like to try this project to calculate genetic correlation between depression and stroke using LD score regression. So I have started following the instruction from the documentation. I have successfully cloned the repository. But when I trying to run following command line, I am facing ImportError which is also described below:

Command line: /usr/local/packages/Python-2.7.8/bin/python ldsc/ldsc.py -h

Error:
Traceback (most recent call last):
  File "ldsc/munge_sumstats.py", line 11, in <module>
    from scipy.stats import chi2
  File "/usr/local/packages/Python-2.7.8/lib/python2.7/site-packages/scipy/stats/__init__.py", line 338, in <module>
    from .stats import *
  File "/usr/local/packages/Python-2.7.8/lib/python2.7/site-packages/scipy/stats/stats.py", line 180, in <module>
    import scipy.special as special
  File "/usr/local/packages/Python-2.7.8/lib/python2.7/site-packages/scipy/special/__init__.py", line 629, in <module>
    from .basic import *
  File "/usr/local/packages/Python-2.7.8/lib/python2.7/site-packages/scipy/special/basic.py", line 18, in <module>
    from . import orthogonal
  File "/usr/local/packages/Python-2.7.8/lib/python2.7/site-packages/scipy/special/orthogonal.py", line 101, in <module>
    from scipy import linalg
  File "/usr/local/packages/Python-2.7.8/lib/python2.7/site-packages/scipy/linalg/__init__.py", line 190, in <module>
    from ._decomp_update import *
  File "scipy/linalg/_decomp_update.pyx", line 1, in init scipy.linalg._decomp_update (scipy/linalg/_decomp_update.c:39096)
ImportError: /usr/local/packages/Python-2.7.8/lib/python2.7/site-packages/scipy/linalg/cython_lapack.so: undefined symbol: zlacn2_

I have installed all required Python modules for the same version of Python which I am using to run the script.

Can someone please help me to solve this issue?

Thanks.

Best,
Tushar

**Comment by rkwalters** [comment]
Hi Tushar,
Thanks for including the full error trace. It looks like scipy is failing to import some low-level math libraries (lapack). This likely means either you are missing those libraries or there’s a compatibility issue between you version of those libraries and your version of scipy. Have you successfully used scipy previously or is this a new install?
Cheers,
Raymond 



------
Raymond K. Walters
Postdoctoral Research Fellow
Analytic & Translational Genetics Unit
Massachusetts General Hospital
rwalters@broadinsitute.org

**Comment by tushardave26** [comment]
Thanks for your prompt response Raymond.

It's a new install. I installed it to use ldsc. Is there any way of checking that which version of that math library scipy requires and which version of that math library is installed my system?

**Comment by rkwalters** [comment]
Hi Tushar,
Unfortunately I’m not aware of an easy direct check of this, and in my experience scipy often tends to be finicky regardless.

Since this is a fresh install, the simplest solution may be to install Anaconda, which includes a package manager and the full stack of common data analysis packages for python. 

If that doesn’t work, lapack implementations are platform dependent, so the first question is: what OS are you trying to install on?

Cheers,
Raymond

**Comment by tushardave26** [comment]
Raymond, answer to your question about what OS am I trying to install LDSC on is RHEL 4. I will give a shot with Anaconda install and keep everybody posted here. Thanks for your help.

**Comment by tushardave26** [comment]
I have installed Anaconda on my system and try to run ldsc.py -h (with the Python that comes with Anaconda i.e. Python2.7.11) and it just works out fine. So I think, now I can use LDSC scripts.

Thanks Raymond for all your help to track down the issue and also for your suggestion for Anaconda.

**Comment by rkwalters** [comment]
Great! Glad that solved it.
Cheers,
Raymond
