### ISSUE TITLE
Causes for Ratio < 0 other than GC?

### ISSUE THREAD

**Issue by tgbrooks** [bulik/ldsc#427]
I am trying to compute genetic correlation on two GWASes, one of which is from [http://www.nealelab.is/uk-biobank](http://www.nealelab.is/uk-biobank). Both of these GWAS control for the first 20 PCs of the genetic data to control population structure.

When running LDSC, I get:

```
Heritability of phenotype 1
---------------------------
Total Observed scale h2: 0.0027 (0.0014)
Lambda GC: 1.0135
Mean Chi^2: 1.0174
Intercept: 0.998 (0.006)
Ratio < 0 (usually indicates GC correction).

Heritability of phenotype 2/2
-----------------------------
Total Observed scale h2: 0.013 (0.0015)
Lambda GC: 1.0772
Mean Chi^2: 1.0832
Intercept: 0.9903 (0.0071)
Ratio < 0 (usually indicates GC correction).
```

I'm concerned about the "Ratio < 0" aspect. Neither study included genetic control as I understand it from [wikipedia](https://en.wikipedia.org/wiki/Genetic_engineering), but could the ratio < 0 be caused by controlling for the 20 PCs?

And do I need to be concerned that Ratio < 0?

**Comment by aksarkar** [comment]
@tgbrooks The reason ldsc reports "Ratio < 0" is that the estimated intercept is < 1. The point estimates and standard errors suggest no residual population structure remains.

I would be more concerned that the estimated heritability is essentially 0. This can make estimates of genetic correlation unreliable.

**Comment by tgbrooks** [comment]
Thank you for the answer!
