### ISSUE TITLE
Individual variant heritabilities?

### ISSUE THREAD

**Issue by danieljrichard** [bulik/ldsc#441]
Hello!
I’m looking to do some analyses regarding heritability (h2) at single-variants overlaying some genetic features (more than annotation enrichment via LDSC, for example). Is there some way to have LDSC produce h2 estimates for individual variants from UKB summary statistics?

Thanks,

Daniel

**Comment by aksarkar** [comment]
@danieljrichard You cannot do this unless you have the phenotype variance.

The proportion of variance explained by a single marker is b^2 V[x] / V[y], where b is the effect size, V[x] = 2 f (1 - f) under HWE, and V[y] is the phenotype variance.

**Comment by danieljrichard** [comment]
Thanks for clarifying! By phenotype variance, do you mean a static number for a trait (similar to how LDSC handles liability scale), or is this an individual-genotype-level thing?

It may be outside the scope, but from the UKB summary statistics I can get 'ytx', or "Dot product of phenotype vector y and genotype vector x (alt allele count in cases for case/control phenotypes)." Would this be helpful at all?

**Comment by aksarkar** [comment]
V[y] is a scalar -- the variance of the phenotype in the population.

In practice, you would need to have the individual level phenotype values for the individuals in the GWAS and plug in the sample variance.

`ytx` is the effect size `b`, up to scaling of genotypes.

**Comment by danieljrichard** [comment]
Great - thanks for clarifying! Much appreciate the support.
