### ISSUE TITLE
"Pip subprocess error" during installation of LDSC 

### ISSUE THREAD

**Issue by dhlee1013** [bulik/ldsc#445]
Hello,

I keep getting the following error when I try to install ldsc: 

##########################################################
(base) [dheonlee@ccebsub1 ldsc]$ conda env create --file environment.yml
Channels:
 - bioconda
 - conda-forge
 - defaults
Platform: linux-64
Collecting package metadata (repodata.json): done
Solving environment: done

Downloading and Extracting Packages:

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
Installing pip dependencies: / Ran pip subprocess with arguments:
['/home/dheonlee/miniconda3/envs/ldsc/bin/python', '-m', 'pip', 'install', '-U', '-r', '/home/dheonlee/ldsc/condaenv.qmk26ht7.requirements.txt', '--exists-action=b']
Pip subprocess output:

Pip subprocess error:
/home/dheonlee/miniconda3/envs/ldsc/bin/python: No module named pip
                                                                                            failed

CondaEnvException: Pip failed
##########################################################

I tried to activate ldsc, install pip module, and update the environment using the codes below, but this attempt failed too.
conda activate ldsc
conda install pip
conda env update --file environment.yml

I would greatly appreciate any advice!

**Comment by AppWick-hub** [comment]
Hi, 
I had also encountered (after trying: conda env create --file environment.yml) the similar issue and I managed to solve it using the following few liners : 

1. First need to install pip (using ensurepip) for the specific python version as follow: 
./envs/ldsc/bin/python -m ensurepip 

May be you need to run: /home/dheonlee/miniconda3/envs/ldsc/bin/python -m ensurepip

2. Then update the conda environment:

conda env update --file environment.yml --name ldsc --prune 

3. Then check further: 

conda activate ldsc 

./ldsc.py -h

**Comment by dhlee1013** [comment]
Thank you so much! Your codes fixed the issue!

**Comment by HelloWorldLTY** [comment]
Thanks for your helpful answer. I think it worths a pull request, I will do that.
