### ISSUE TITLE
How to update the partitioned LDscore?

### ISSUE THREAD

**Issue by Jesson-mark** [bulik/ldsc#448]
Hi, 
thanks for the great software! 

I'm using S-LDSC to partition herititability for my GWAS and our eQTLs datasets. I already created two types of annot files and LDscore files (containing two types of eQTLs: nominal eQTLs and max PIP of eQTLs) as that in GTEx. 

I noticed that the LDscores of all annotations except eQTLs annotations are same in the two types of LDscore files. For example, the baseL2, Coding_UCSC.bedL2, ..., Human_Promoter_Villar_ExAC.flanking.500L2 are all same! Since calculating LDscore from the annot file is a little time-consuming (about 2.5 days for chr1), I wonder if I can calculate LDscore for the additional annotation then merge it with pre-calculated LDscore of other annotations?

**Comment by aksarkar** [comment]
Yes, you can append the new column name to the header and the new values to each row.

**Comment by Jesson-mark** [comment]
Thanks for your useful reply! I'll have a try.
