### ISSUE TITLE
HapMap3 SNPs link

### ISSUE THREAD

**Issue by sgagliano** [bulik/ldsc#45]
Hi, 

The link for the list of HapMap3 SNPs under Part 1 of the Partitioned Heritability page (https://github.com/bulik/ldsc/wiki/Partitioned-Heritability) isn't working for me. The following error comes up: "You don't have permission to access /~bulik/w_hm3.snplist.bz2 on this server."

Thanks.

Sarah

**Comment by rkwalters** [comment]
Hi Sarah,
The correct location for that file is: https://data.broadinstitute.org/alkesgroup/LDSCORE/w_hm3.snplist.bz2

Looks like I missed that link when we relocated the file. Should be fixed now.

Cheers,
Raymond




On Mar 7, 2016, at 9:35 AM, sgagliano <notifications@github.com> wrote:

> Hi,
> 
> The link for the list of HapMap3 SNPs under Part 1 of the Partitioned Heritability page (https://github.com/bulik/ldsc/wiki/Partitioned-Heritability) isn't working for me. The following error comes up: "You don't have permission to access /~bulik/w_hm3.snplist.bz2 on this server."
> 
> Thanks.
> 
> Sarah
> 
> �
> Reply to this email directly or view it on GitHub.
> 




------
Raymond K. Walters
Postdoctoral Research Fellow
Analytic & Translational Genetics Unit
Massachusetts General Hospital
rwalters@broadinsitute.org

**Comment by sgagliano** [comment]
Thank you!

Sarah
