### ISSUE TITLE
How to obtain per-SNP heritability by LDSC?

### ISSUE THREAD

**Issue by Jesson-mark** [bulik/ldsc#451]
Hi, 
I'm currently using LDSC to estimate the heritability of a polygenic trait. 

I already estimated the total heritability (variance explained by all genome-wide SNPs) of this trait. 
Since now I focused on a specific SNP and want to evaluate the relative contribution of this SNP to the trait, how to calculate the per-SNP heritability by LDSC?  

Since LDSC can calculate the total heritability, it may already have the per-SNP heritability calculated. Do you have any suggestion to extract that?

Any input will be appreciated!

**Comment by aksarkar** [comment]
The variance explained by a single SNP x is b^2 V[x] / V[y], where b is the effect size, V[x] is the variance of the genotypes, and V[y] is the variance of the phenotype.

**Comment by Jesson-mark** [comment]
Thanks for your quick reply! 

I should refine my question! Since I don't have the genotype and phenotype data, how to calculate the variance explained by a single SNP using only GWAS summary statistics? Is there a formula relating the effect size and frequency of this SNP to the variance explained?

**Comment by aksarkar** [comment]
Under HWE, V[x] = 2 f (1 - f) where f is the MAF.

But if you don't have V[y], or cannot safely assume that V[y] = 1 (that is, effect sizes are standardized), then you still cannot use this to estimate the PVE of a single SNP.

**Comment by Jesson-mark** [comment]
Thanks for your helpful reply!
