### ISSUE TITLE
1000G.mac5eur.* files

### ISSUE THREAD

**Issue by sgagliano** [bulik/ldsc#46]
Hi, 

The 1000G.mac5eur.* files referred to in Step 1 of the Partitioned Heritability page do not seem to be on https://data.broadinstitute.org/alkesgroup/LDSCORE/. 

Thanks.

Sarah

**Comment by hilaryfinucane** [comment]
Hi Sarah,

They are in 1000G_plinkfiles.tgz and 1000G_frq.tgz.

Best,

Hilary

**Comment by sgagliano** [comment]
Thank you!

Sarah

**Comment by PeteHaitch** [comment]
FYI I also got lost trying to find these files
