### ISSUE TITLE
Unexpected genetic correlation (rg) estimate

### ISSUE THREAD

**Issue by dtomi0223** [bulik/ldsc#468]
When running LDSC with the --rg command, I observed that the heritability estimates for two traits (BMI and blood pressure) were as expected. However, the genetic correlation (rg) value was much smaller than anticipated.

Details:
-Trait 1: BMI (https://atlas.ctglab.nl/traitDB/4044)
-Trait 2: Blood pressure (https://atlas.ctglab.nl/traitDB/4378)
-GWAS summary statistics were obtained from the links provided on GWAS ATLAS for both traits
-The SNPh2, LambdaGC, Chi2, and Intercept values from my LDSC analysis were consistent with those reported on GWAS ATLAS for each trait individually
-GWAS ATLAS reports a genetic correlation of 0.363 between these traits, which seems intuitively correct
-My LDSC analysis produced a much smaller rg value of -0.076

LDSC command used:
ldsc.py \
--rg /home/parallels/Documents/MetS/Meta-analysis_Wood_et_al+UKBiobank_2018_with_Z_munged.sumstats.gz,/home/parallels/Documents/MetS/ZhuZ_30940143_ukbb.bolt_460K_selfRepWhite.doctor_highbloodpressure.assoc_with_Z_munged.sumstats.gz \
--ref-ld-chr /home/parallels/ldsc_data/eur_w_ld_chr/ \
--w-ld-chr /home/parallels/ldsc_data/eur_w_ld_chr/ \
--out ~/Documents/MetS/bmi_bp_ldsc_20241206_2

Results:
Heritability of phenotype 1 (BMI):
  Total Observed scale h2: 0.4933 (0.0219)
  Lambda GC: 3.6129
  Mean Chi^2: 8.4604
  Intercept: 1.6481 (0.1124)
  Ratio: 0.0869 (0.0151)
Heritability of phenotype 2 (Blood pressure):
  Total Observed scale h2: 0.1272 (0.0055)
  Lambda GC: 1.7648
  Mean Chi^2: 2.2126
  Intercept: 1.0978 (0.0196)
  Ratio: 0.0806 (0.0162)
Genetic Covariance:
  Total Observed scale gencov: -0.019 (0.0048)
  Mean z1*z2: -0.322
  Intercept: -0.0632 (0.0175)
Genetic Correlation:
  Genetic Correlation: -0.076 (0.019)
  Z-score: -4.0055
  P: 6.1877e-05

Additional information:
Munge_sumstats was conducted using --merge-alleles ~/ldsc_data/w_hm3.snplist, obtained from https://ibg.colorado.edu/cdrom2021/Day06-nivard/GenomicSEM_practical/eur_w_ld_chr/w_hm3.snplist
LD scores were obtained from https://ibg.colorado.edu/cdrom2021/Day06-nivard/GenomicSEM_practical/eur_w_ld_chr

This discrepancy in rg estimates is puzzling, given that the individual trait heritability estimates are consistent with expectations. I'm seeking insights into potential causes for this unexpected result. Thank you for your cooperation.

**Comment by TingyanY** [comment]
Hi there,

I came across the same issue recently, and I am wondering do you have any thoughts/insight about it? 
Thank you!

Cheers,
Tingyan
