### ISSUE TITLE
How can I perform genetic correlation of two traits from different population? European versus Asian.

### ISSUE THREAD

**Issue by amarawi** [bulik/ldsc#52]

**Comment by rkwalters** [comment]
Hi @amarawi,
This kind of cross-population analysis is not currently possible with LD Score regression. 

LD Score regression depends on the expected degree of tagging for polygenic signal based on the local LD structure, but that model of relationship with LD is violated when considering correlation for two traits with strongly differing LD structures. It's possible that the base LD score model can be adapted to correctly model this cross-ancestry structure, and that remains an active area of research, but for the moment there's no recommended way to implement this analysis in ldsc.

Cheers,
Raymond

**Comment by bulik** [comment]
You might be interested in [this pre-print](http://biorxiv.org/content/early/2016/02/23/036657)

**Comment by rkwalters** [comment]
Hi,
The pre-print Brendan mentioned is now published, and code is publicly available at:
https://github.com/brielin/Popcorn

I'm closing this issue thread as inactive/resolved, but if you still have questions about this or any other issues feel free to follow up here or via [the google group](https://groups.google.com/forum/#!forum/ldsc_users).

Cheers,
Raymond
