### ISSUE TITLE
Specifying sample size when GWAS included related individuals

### ISSUE THREAD

**Issue by painoh** [bulik/ldsc#53]
Hello,

I have performed a GWAS for a quantitative trait using a twin sample containing MZ and DZ siblings. To account for the effect of shared environment between siblings, I used a general estimating equation as described here: http://www.nature.com/mp/journal/v19/n11/full/mp2014121a.html

I would like to use the results in LD Score regression. Am I correct in thinking that I need to calculate and use the effective sample size?

Thanks,

Ollie

**Comment by rkwalters** [comment]
Hi Ollie,
This is not something we’ve tested yet, but my hunch would be that using the effective sample size is probably the correct answer (and I would suspect that even if it’s not perfectly right it’s almost certainly better than using the raw sample size in this case). 
Cheers,
Raymond

**Comment by painoh** [comment]
Hi Raymond,

Thanks for the quick response. I will go forward specifying the effective sample size which can be easily calculated using the formula in the reference above.

Regards,

Ollie
