### ISSUE TITLE
Understanding results from LD regression

### ISSUE THREAD

**Issue by EmmaO94** [bulik/ldsc#56]
I've recently run an LD regression and the results are confusing me slightly.

Genetic Correlation
-------------------
Genetic Correlation: 0.9108 (2.6371)
Z-score: 0.3454
P: 0.7298

above is says genetic correlation is 0.91 yet in the summary of results:

Summary of Genetic Correlation Results
p1                              p2      rg      se       z       p  h2_obs  h2_obs_se  h2_int  h2_int_se  gcov_int  gcov_int_se
PrunedFemSumStats.sumstats.gz  PrunedMaleSumStats.sumstats.gz  0.9108  2.6371  0.3454  0.7298  0.0473     0.1835  1.0225     0.0112    0.0142       0.0074

assuming the third number value along is rg (which I've been told is genetic correlation), says 0.3454, but in the genetic correlation section the z-score is 0.3454.

Is the Z score also the rG?
Also is the P in the Genetic Correlation section the significance of the genetic correlation?

**Comment by rkwalters** [comment]
Answered on the LD Score user group here:
https://groups.google.com/d/msg/ldsc_users/YjXXLL7qHTw/SrdqmSxvBQAJ

Closing the github issues as resolved, but feel free to continue the conversation on the user group if there are additional questions on this topic.
