### ISSUE TITLE
LD Hub website documentation issues

### ISSUE THREAD

**Issue by gwern** [bulik/ldsc#57]
I recently tried to use LD Hub for getting genetic correlations with the education polygenic score reported in Okbay et al 2016 and looking at the genetic correlation matrix with all the other traits. I ran into a number of issues:
- it is unclear where one goes to report bugs or issues with LD Hub. The front page and about links http://ldsc.broadinstitute.org/about/ do not provide any emails or Github links. The software tab links to https://github.com/bulik/ldsc which doesn't mention LD Hub at all.
- sessions expire too quickly and one has to log in repeatedly; this also interrupts uploads, apparently - an upload can just terminate halfway through
- the available genetic correlation matrix in the Lookup Center is out of date: there are 173 traits with SNP heritabilities available (and so I assume have full data and can be used for genetic correlations as well), but only 49 traits are listed in the genetic correlation page! It's nice to provide the exact correlation data for the original LD Hub paper, but why not provide the old 49x49 matrix somewhere else (perhaps linking it on the Lookup Center page) and update it with the full 173x173 correlation matrix?
- naming of traits is inconsistent from the SNP heritabilities list to the genetic correlation spreadsheet
- GWAShare Center page is unclear: who is allowed to contribute under what basis? Must a consortium/lead author authorize an upload, or is any public dataset fair game? I wanted to see genetic correlations for the 'years of education' variable from the new study Okbay et al 2016 (available [on SSGAC's website](http://www.thessgac.org/#!data/kuzq8), `EduYears_Main.txt`) which obsoletes the existing LD Hub 'years of education' variable which is based on Rietveld et al 2013, but I don't know if I am allowed to upload that (or any other) dataset or not.
- Test Center documentation is unclear about the requirements for an uploaded file. Does the header format have to be _exactly_ "snpid   A1  A2  Z (or beta)     N   P-value"? I assume "Z (or beta)" actually means "Z" or "beta". A column name of "P-value" is quite awkward for R users, since by default you can't even create a dataframe with that as a column name (it will be automatically converted to "P.value" instead for safety, and this has to be overridden using `check.names=FALSE`). Does the ZIP filename have to be _exactly_ "file"++".zip"? After a lot of experimentation, I also discovered that apparently any quotes anywhere in the upload file will break the upload, which is quite surprising for a CSV file upload.
- the upload & analysis process doesn't do any kind of error-checking, it seems, so an upload can fail but one doesn't realize this until you download the results and inspect them manually
- when uploading, it would be very helpful if the interface could provide some information about where one is in the process, so one could know when an error popped up. I ran into issues with the formatting but I initially attributed it to incomplete uploads since the file is so big (178M). (Support for `.xz` uploads would also help with uploads since LZMA-style compessors can cut these files' sizes substantially.)

If anyone is curious, this is how I managed to get the Okbay et al 2016 polygenic score (using `EduYears_Main.txt`) to eventually work with LD Hub:

``` .R
okbay <- read.table("EduYears_Main.txt", header=TRUE)
## SSGAC file format: "MarkerName      CHR     POS     A1      A2      EAF     Beta    SE      Pval"
## LD Hub file format: "snpid   A1  A2  Z (or beta)     N   P-value"
## select just the ones we need:
okbay <- subset(okbay, select=c("MarkerName", "A1", "A2", "Beta", "Pval"))
## SSGAC->LD Hub names
## rearrange to put N before P-value
okbay <- with(okbay, data.frame(snpid=MarkerName, A1=A1, A2=A2, beta=Beta, N=293723+111439, "P-value"=Pval, check.names=FALSE))
write.table(okbay, file="2016-okbay-eduyears.txt", row.names=FALSE, quote=FALSE, sep="\t")
system("zip 2016-okbay-eduyears.txt.zip 2016-okbay-eduyears.txt")
# https://www.dropbox.com/s/rfvetxywppmxega/EduYears_Main.txt.zip
```

**Comment by hilaryfinucane** [comment]
Hi,

There will soon be a dedicated email list for LD Hub-related questions. In
the meantime, please direct your questions about LD Hub to Jie Zheng (
Jie.Zheng@bristol.ac.uk).

Thanks,

Hilary

**Comment by gwern** [comment]
I've forwarded my comments to Jie Zheng.

**Comment by gwern** [comment]
Zheng has not replied to my email, so I think you guys have to fix these issues on your own.

**Comment by rkwalters** [comment]
Hi,
The issues you reported are related to the LD Hub web interface rather than the ldsc analysis software, so unfortunately the only part we can really address here is documenting who to contact with questions/bug reports. We've updated the readme to include the contact email for the LD Hub project (pull #60), and it looks like ldsc.broadinsititute.org now has a contact email on it's front page, so hopefully that will make it easier to find and contact the relevant support team.

Hopefully Jie (Chris) Zheng and colleagues will be able to address your remaining points on LD Hub.

Cheers,
Raymond

**Comment by rkwalters** [comment]
Hi,
I'm hoping this eventually got addressed by the LD Hub team? I'm closing this issue thread as inactive (has been ~6 months since the last comment), but if you have any more issues feel free to follow up with the appropriate contact (ld-hub@bristol.ac.uk for LD Hub issues, or [the google group](https://groups.google.com/forum/?hl=en#!forum/ldsc_users) for ldsc issues).
Cheers,
Raymond
