### ISSUE TITLE
missing file from pat. heritability tutorial

### ISSUE THREAD

**Issue by kasperdanielhansen** [bulik/ldsc#61]
The partitioned h2 tutorial at `https://github.com/bulik/ldsc/wiki/Partitioned-Heritability` mentions `1000G.mac5eur.*` file and says they can be found at `https://data.broadinstitute.org/alkesgroup/LDSCORE/`. Yet, I don't see them.

**Comment by kasperdanielhansen** [comment]
Issue #46 says they can be found inside some of the tarballs.   Perhaps mention this on tutorial page

**Comment by kasperdanielhansen** [comment]
Confirmed they're inside tarballs.

**Comment by rkwalters** [comment]
Hi Kasper,
Glad you were able to find them. I’ve updated the wiki to clarify the files to be downloaded for the partitioned heritability tutorial.

@PeteHaitch: Thanks for reporting this also.

Cheers,
Raymond
