### ISSUE TITLE
Stratified h2

### ISSUE THREAD

**Issue by DCousminer** [bulik/ldsc#67]
1. How do I find the h2_Z for my trait?

2. When estimating partitioned h2 for cell type categories, should the prop_h2 be 1 for all categories?

Thanks!

**Comment by rkwalters** [comment]
Hi,

1. Do you mean the Z score for testing the estimate of total snp-h2? That would be z = h2 / se. The se is the value given in parentheses after the h2 estimate in the ldsc output.

2. No. Assuming you’re using the default standard categories, only “base” (the baseline annotation containing all SNPs) is expected to have prop_h2=1. 

Cheers,
Raymond

**Comment by rkwalters** [comment]
Hi,
I'm closing this issue thread as resolved since it's been a few months since the last comment, but if you have any more issues feel free to follow up here or via [the google group](https://groups.google.com/forum/?hl=en#!forum/ldsc_users).
Cheers,
Raymond
