### ISSUE TITLE
GC corrected data: Undo

### ISSUE THREAD

**Issue by guruprem** [bulik/ldsc#70]
Hi, 

Is there a way to undo the GC correction of the summary data for LDSC rg. Since the GC correction can lead to downward bias estimates. Will be of great help if you can advise me on this.

Thanks so much in advance.

Regards
Murali

**Comment by rkwalters** [comment]
Hi Murali,
If you know the lambdaGC value that was used and the GC was only done on the final GWAS (i.e. it’s not a meta-analysis with GC on each separate cohort), then multiplying the GWAS chi square values by lambdaGC should be sufficient to undo the GC.

In the case of meta-analysis with GC on each cohort, it’s possible but more complicated. Proposition 3 (formula 4.3) in the supplement of the first LD score paper (doi:10.1038/ng.3211) gives the expected chi square in this scenario given lambdaGC for each cohort. LDSC doesn’t have a direct way to supply lambda values to use this computation, but you should be able to get the intended effect by inputting a modified sample size that reflects the expression for N in formula 4.3.

Cheers,
Raymond

**Comment by rkwalters** [comment]
Hi Murali,
I'm closing this issue thread as resolved since it's been 2 months since the last comment, but if you still have questions about GC correction or any other issues feel free to follow up here or via [the google group](https://groups.google.com/forum/#!forum/ldsc_users).
Cheers,
Raymond
