### ISSUE TITLE
Different h2 from the same sumstats.gz file using --h2 flag and --rg flag

### ISSUE THREAD

**Issue by Kyoko-wtnb** [bulik/ldsc#74]
Hi,

I have computed h2 for a phenotype with --h2 flag and also computed rg with another phenotype with --rg flag. However I've got NA for rg since h2 estimated with --rg flag was negative even thought h2 was above 0 with --h2 flag for the same file.

Only the difference I could notice was there was one more filtering in --rg and I assume because of this I got different h2. Could you explain what it does and which h2 I should use?
I am aware that when h2 is very close to 0, rg is no longer informative but I am using ldsc for lots of other phenotypes too, so I'd like to know what is the explanation for this difference.

**The results with --h2 flag**
------------------------
Beginning analysis at Mon Feb 13 17:03:33 2017
Reading summary statistics from 817/ldsc.sumstats.gz ...
Read summary statistics for 1180704 SNPs.
Reading reference panel LD Score from data/eur_ldscores/[1-22] ...
Read reference panel LD Scores for 1293150 SNPs.
Removing partitioned LD Scores with zero variance.
Reading regression weight LD Score from data/eur_ldscores/[1-22] ...
Read regression weight LD Scores for 1293150 SNPs.
After merging with reference panel LD, 1175563 SNPs remain.
After merging with regression SNP LD, 1175563 SNPs remain.
Using two-step estimator with cutoff at 30.
Total Observed scale h2: 0.0087 (0.0397)
Lambda GC: 1.0075
Mean Chi^2: 1.0155
Intercept: 1.0131 (0.0074)
Ratio: 0.8483 (0.4767)

**The results with --rg flag**
---------------------------
Beginning analysis at Thu Feb 23 13:02:33 2017
Reading summary statistics from 817/ldsc.sumstats.gz ...
Read summary statistics for 1180704 SNPs.
Reading reference panel LD Score from /data/ldsc/eur_ldscores/[1-22] ...
Read reference panel LD Scores for 1293150 SNPs.
Removing partitioned LD Scores with zero variance.
Reading regression weight LD Score from /data/ldsc/eur_ldscores/[1-22] ...
Read regression weight LD Scores for 1293150 SNPs.
After merging with reference panel LD, 1175563 SNPs remain.
After merging with regression SNP LD, 1175563 SNPs remain.
Computing rg for phenotype 2/380
Reading summary statistics from 1/ldsc.sumstats.gz ...
Read summary statistics for 1217311 SNPs.
After merging with summary statistics, 1175563 SNPs remain.
1020224 SNPs with valid alleles.

Heritability of phenotype 1
Total Observed scale h2: -0.004 (0.0387)
Lambda GC: 1.0075
Mean Chi^2: 1.015
Intercept: 1.0161 (0.0083)
Ratio: 1.0704 (0.5526)

Best,
Kyoko

**Comment by rkwalters** [comment]
Hi Kyoko,
As you’ve correctly noted there is a difference in the filtering between the two analyses, and that’s responsible for the difference in the estimates. The rg analysis is filtering to variants present for both GWAS so that the estimated h2 corresponds to the genetic covariance estimate for conversion to rg. 

In most cases the estimate from --h2 is probably the one you’d want to report, though the difference is usually nominal (as is the case for the .01 difference here, it’s just more noticeable since you’re right against the boundary of h2=0). 

Cheers,
Raymond

**Comment by Kyoko-wtnb** [comment]
Hi Raymond,

Thank you for your clear explanation!!

Best,
Kyoko

**Comment by rkwalters** [comment]
Hi Kyoko,
I'm closing this issue thread as resolved, but if you have any more issues feel free to follow up here or via [the google group](https://groups.google.com/forum/?hl=en#!forum/ldsc_users).
Cheers,
Raymond
