### ISSUE TITLE
only p values no beta

### ISSUE THREAD

**Issue by mhsteppan** [bulik/ldsc#76]
Hi guys,
is it possible to calculate genetic correlation, if I only have p values and a sign (+ or -) indicating the direction of the effect, but no actual betas? Obviously p values and absolute betas are highly correlated, so I could more or less accurately predict my betas based on other datasets. But is there a technical solution in the ldsc package for my data situation?
Kind regards,
Martin

**Comment by rkwalters** [comment]
Hi Martin,
I believe munge_sumstats.py can be manipulated to handle this correctly if you convert the signs to numeric +1/-1, and then indicate that column as the --signed-sumstat (with null value = 0). This should be equivalent to the manual solution, which is using the p-value and sign to convert to the corresponding signed z-score. 
Cheers,
Raymond

**Comment by mhsteppan** [comment]
Thanks! sorry did not close the issue.
