### ISSUE TITLE
latest release

### ISSUE THREAD

**Issue by 0xaf1f** [bulik/ldsc#86]
We received a user request to install ldsc on our cluster, but your latest release is from 2015 and the README advises using the master branch despite naming the 1.0.0 release in the title. In order to avoid getting partial states of development, we'd rather not install directly out of the master branch.

Would you mind rounding out the development and tagging a new release? If the current state is releasable, tagging it as such would be nice. Thanks for your consideration.

**Comment by tpoterba** [comment]
Hi @0xaf1f, 
LDSC is not currently under active development. We do our best to maintain it with bug fixes, but don't have any plans for new releases. The master branch can be tracked with the git hash, and is as polished as it would be if we tagged each commit by incrementing some 1.0.x version number.

**Comment by 0xaf1f** [comment]
Ok, I will use `git describe` to make a version string. Although there's nothing wrong with having a bunch of minor versions, especially when `git tag` is not expensive.
